import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Muhammad Imron</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h5 className={styles.title}>
          Welcome to <a href="https://wtg.nasihosting.com">Cek di sini</a>
        </h5>

        <p className={styles.description}>
           Bio Link {' '}
          <code className={styles.code}>OPS SDN 1 WATUGEDE</code>
        </p>

        <div className={styles.grid}>
          <a href="https://docs.google.com/spreadsheets/d/1Ri-cBJCrNMYeeYXbPLFVlYve1YkY5mfI/edit?usp=sharing&ouid=114749342650366024498&rtpof=true&sd=true" className={styles.card}>
            <h2>SKP UMI WAHYUNI &rarr;</h2>
            <p>SKP di sini <a href="https://docs.google.com/spreadsheets/d/1Ri-cBJCrNMYeeYXbPLFVlYve1YkY5mfI/edit?usp=sharing&ouid=114749342650366024498&rtpof=true&sd=true">Cek di sini</a> </p>
          </a>

          <a href="https://docs.google.com/spreadsheets/d/1DwYU52pLbawZLfX4xA-q1aLKjGnFGu0E/edit?usp=sharing&ouid=114749342650366024498&rtpof=true&sd=true" className={styles.card}>
            <h2>SKP DWI AGUSTIN &rarr;</h2>
            <p>Cek Disini</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{'Muhammad Imron'}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
